### ISSUE TITLE
s3cmd commands not using s3:// protocol

### ISSUE THREAD

**Issue by srbartlett** [richie/capistrano-s3-copy#1]
I am received the following error when the "s3cmd get" command is run on the remote server.

ERROR: Parameter problem: Expecting S3 URI instead of '[BUCKET_NAME]:production/20121010043909.tar.gz'

It appears to be missing the s3:// protocol?

The previous command "s3cmd put" which is run locally is happy - it too doesn't have s3://  

Is it just me - am I doing something wrong?

I can submit a pull request should you require

**Comment by richie** [comment]
Apologies, I've been consumed by work lately. So the root problem here is that I mention the wrong s3cmd in the README. The command-line s3 tool I actually used was from here: https://github.com/s3tools/s3cmd - this supports the s3:// style URLs.

I will fix the docs.
